import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const archiveSans = localFont({
  src: "../public/fonts/OTF/경기천년제목OTF_Medium.otf",
  variable: "--font-archive-sans",
  display: "swap",
});

const archiveSerif = localFont({
  src: "../public/fonts/OTF/경기천년바탕OTF_Regular.otf",
  variable: "--font-archive-serif",
  display: "swap",
});

const archiveTitleLight = localFont({
  src: "../public/fonts/OTF/경기천년제목OTF_Light.otf",
  variable: "--font-archive-title-light",
  display: "swap",
});

const archiveTitleMedium = localFont({
  src: "../public/fonts/OTF/경기천년제목OTF_Medium.otf",
  variable: "--font-archive-title-medium",
  display: "swap",
});

const archiveTextSemibold = localFont({
  src: "../public/fonts/OTF/경기천년바탕OTF_Bold.otf",
  variable: "--font-archive-text-semibold",
  display: "swap",
});

const archiveTitleBold = localFont({
  src: "../public/fonts/OTF/경기천년제목OTF_Bold.otf",
  variable: "--font-archive-title-bold",
  display: "swap",
});

const archiveTitleBlack = localFont({
  src: "../public/fonts/OTF/경기천년제목OTFV_Bold.otf",
  variable: "--font-archive-title-black",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="ko"
      className={`${archiveSans.variable} ${archiveSerif.variable} ${archiveTitleLight.variable} ${archiveTitleMedium.variable} ${archiveTextSemibold.variable} ${archiveTitleBold.variable} ${archiveTitleBlack.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
